In [2]:
! pip install phpserialize

Collecting phpserialize
  Downloading phpserialize-1.3.tar.gz (7.5 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: phpserialize
  Building wheel for phpserialize (pyproject.toml): started
  Building wheel for phpserialize (pyproject.toml): finished with status 'done'
  Created wheel for phpserialize: filename=phpserialize-1.3-py3-none-any.whl size=9556 sha256=3120185cc1dd84261a1772e28e3b39937bfeb270e41c76b38bc5b39d31c1e436
  Stored in directory: c:\users\charl\appdata\local\pip\cache\wheels\65\cc\0f\7dd6fc6d90172103219784e7120e124e9845a33f21ee5b52b2
Successfully built phpserialize
Installing collected packages: phpserialize
Successfully installed phpserialize-1.3

In [1]:
import numpy as np
import pandas as pd
import phpserialize
import json

In [4]:
with open("views_config.bin", "rb") as f:
    php_data = f.read()

data = phpserialize.loads(php_data, decode_strings=True)

print(json.dumps(data, indent=2, ensure_ascii=False))

{
  "uuid": "31c13ab9-0aad-4542-a3bd-8f9f2a501382",
  "langcode": "en",
  "status": true,
  "dependencies": {
    "config": {
      "0": "node.type.documents",
      "1": "node.type.people",
      "2": "system.menu.project-tools"
    },
    "module": {
      "0": "node",
      "1": "user"
    }
  },
  "_core": {
    "default_config_hash": "C9VazN6t5R5JLVIquPoq1urKTnH0dQUAUiGw7SkGY4k"
  },
  "id": "people_roles",
  "label": "People & Roles",
  "module": "views",
  "description": "",
  "tag": "",
  "base_table": "node_field_data",
  "base_field": "nid",
  "display": {
    "default": {
      "id": "default",
      "display_title": "Default",
      "display_plugin": "default",
      "position": 0,
      "display_options": {
        "title": "All People",
        "fields": {
          "title": {
            "id": "title",
            "table": "node_field_data",
            "field": "title",
            "relationship": "none",
            "group_type": "group",
            "admin_label": "",
            "entity_type": "node",
            "entity_field": "title",
            "plugin_id": "field",
            "label": "",
            "exclude": false,
            "alter": {
              "alter_text": false,
              "make_link": false,
              "absolute": false,
              "word_boundary": false,
              "ellipsis": false,
              "strip_tags": false,
              "trim": false,
              "html": false
            },
            "element_type": "",
            "element_class": "",
            "element_label_type": "",
            "element_label_class": "",
            "element_label_colon": true,
            "element_wrapper_type": "",
            "element_wrapper_class": "",
            "element_default_classes": true,
            "empty": "",
            "hide_empty": false,
            "empty_zero": false,
            "hide_alter_empty": true,
            "click_sort_column": "value",
            "type": "string",
            "settings": {
              "link_to_entity": true
            },
            "group_column": "value",
            "group_columns": {},
            "group_rows": true,
            "delta_limit": 0,
            "delta_offset": 0,
            "delta_reversed": false,
            "delta_first_last": false,
            "multi_type": "separator",
            "separator": ", ",
            "field_api_classes": false
          }
        },
        "pager": {
          "type": "mini",
          "options": {
            "offset": 0,
            "pagination_heading_level": "h4",
            "items_per_page": 50,
            "total_pages": null,
            "id": 0,
            "tags": {
              "next": "››",
              "previous": "‹‹"
            },
            "expose": {
              "items_per_page": true,
              "items_per_page_label": "Items per page",
              "items_per_page_options": "5, 10, 25, 50",
              "items_per_page_options_all": true,
              "items_per_page_options_all_label": "- All -",
              "offset": false,
              "offset_label": "Offset"
            }
          }
        },
        "exposed_form": {
          "type": "basic",
          "options": {
            "submit_button": "Apply",
            "reset_button": false,
            "reset_button_label": "Reset",
            "exposed_sorts_label": "Sort by",
            "expose_sort_order": true,
            "sort_asc_label": "Asc",
            "sort_desc_label": "Desc"
          }
        },
        "access": {
          "type": "perm",
          "options": {
            "perm": "access content"
          }
        },
        "cache": {
          "type": "time",
          "options": {
            "results_lifespan": 1800,
            "results_lifespan_custom": 0,
            "output_lifespan": 1800,
            "output_lifespan_custom": 0
          }
        },
        "empty": {},
        "sorts": {
          "title": {
            "id": "title",
            "table": "node_field_data",
            "field": "title",
            "relationship": "none",
            "group_type": "group",
            "admin_label": "",
            "entity_type": "node",
            "entity_field": "title",
            "plugin_id": "standard",
            "order": "ASC",
            "expose": {
              "label": "",
              "field_identifier": ""
            },
            "exposed": false
          }
        },
        "arguments": {
          "title": {
            "id": "title",
            "table": "node_field_data",
            "field": "title",
            "relationship": "none",
            "group_type": "group",
            "admin_label": "",
            "entity_type": "node",
            "entity_field": "title",
            "plugin_id": "string",
            "default_action": "ignore",
            "exception": {
              "value": "all",
              "title_enable": false,
              "title": "All"
            },
            "title_enable": false,
            "title": "",
            "default_argument_type": "fixed",
            "default_argument_options": {
              "argument": ""
            },
            "summary_options": {
              "base_path": "",
              "count": true,
              "override": false,
              "items_per_page": 25
            },
            "summary": {
              "sort_order": "asc",
              "number_of_records": 0,
              "format": "default_summary"
            },
            "specify_validation": true,
            "validate": {
              "type": "none",
              "fail": "not found"
            },
            "validate_options": {},
            "glossary": true,
            "limit": 1,
            "case": "upper",
            "path_case": "lower",
            "transform_dash": false,
            "break_phrase": false
          }
        },
        "filters": {
          "type": {
            "id": "type",
            "table": "node_field_data",
            "field": "type",
            "entity_type": "node",
            "entity_field": "type",
            "plugin_id": "bundle",
            "value": {
              "people": "people"
            },
            "expose": {
              "operator_limit_selection": false,
              "operator_list": {}
            }
          }
        },
        "style": {
          "type": "grid",
          "options": {
            "grouping": {},
            "columns": 3,
            "automatic_width": true,
            "alignment": "vertical",
            "row_class_custom": "",
            "row_class_default": true,
            "col_class_custom": "",
            "col_class_default": true
          }
        },
        "row": {
          "type": "fields",
          "options": {
            "default_field_elements": true,
            "inline": {},
            "separator": "",
            "hide_empty": false
          }
        },
        "query": {
          "type": "views_query",
          "options": {
            "query_comment": "",
            "disable_sql_rewrite": false,
            "distinct": false,
            "replica": false,
            "query_tags": {}
          }
        },
        "relationships": {},
        "css_class": "project-ids",
        "use_ajax": true,
        "header": {},
        "footer": {},
        "display_extenders": {}
      },
      "cache_metadata": {
        "max-age": -1,
        "contexts": {
          "0": "languages:language_content",
          "1": "languages:language_interface",
          "2": "url",
          "3": "url.query_args",
          "4": "user.node_grants:view",
          "5": "user.permissions"
        },
        "tags": {}
      }
    },
    "attachment_1": {
      "id": "attachment_1",
      "display_title": "Attachment",
      "display_plugin": "attachment",
      "position": 2,
      "display_options": {
        "pager": {
          "type": "none",
          "options": {
            "offset": 0
          }
        },
        "arguments": {
          "title": {
            "id": "title",
            "table": "node_field_data",
            "field": "title",
            "relationship": "none",
            "group_type": "group",
            "admin_label": "",
            "entity_type": "node",
            "entity_field": "title",
            "plugin_id": "string",
            "default_action": "summary",
            "exception": {
              "value": "all",
              "title_enable": false,
              "title": "All"
            },
            "title_enable": false,
            "title": "",
            "default_argument_type": "fixed",
            "default_argument_options": {
              "argument": ""
            },
            "summary_options": {
              "base_path": "",
              "count": true,
              "override": false,
              "items_per_page": 25
            },
            "summary": {
              "sort_order": "asc",
              "number_of_records": 0,
              "format": "default_summary"
            },
            "specify_validation": false,
            "validate": {
              "type": "none",
              "fail": "not found"
            },
            "validate_options": {},
            "glossary": true,
            "limit": 1,
            "case": "upper",
            "path_case": "lower",
            "transform_dash": false,
            "break_phrase": false
          }
        },
        "style": {
          "type": "default",
          "options": {
            "grouping": {},
            "row_class": "",
            "default_row_class": true
          }
        },
        "row": {
          "type": "fields",
          "options": {
            "default_field_elements": true,
            "inline": {},
            "separator": "",
            "hide_empty": false
          }
        },
        "defaults": {
          "style": false,
          "row": false,
          "arguments": false
        },
        "display_extenders": {},
        "displays": {
          "page_1": "page_1"
        },
        "inherit_arguments": false,
        "inherit_exposed_filters": true
      },
      "cache_metadata": {
        "max-age": -1,
        "contexts": {
          "0": "languages:language_content",
          "1": "languages:language_interface",
          "2": "url",
          "3": "user.node_grants:view",
          "4": "user.permissions"
        },
        "tags": {}
      }
    },
    "block_1": {
      "id": "block_1",
      "display_title": "Mentioned",
      "display_plugin": "block",
      "position": 3,
      "display_options": {
        "title": "Documents Mentioned In",
        "fields": {
          "title": {
            "id": "title",
            "table": "node_field_data",
            "field": "title",
            "relationship": "reverse__node__field_all_people",
            "group_type": "group",
            "admin_label": "",
            "entity_type": "node",
            "entity_field": "title",
            "plugin_id": "field",
            "label": "",
            "exclude": false,
            "alter": {
              "alter_text": false,
              "text": "",
              "make_link": false,
              "path": "",
              "absolute": false,
              "external": false,
              "replace_spaces": false,
              "path_case": "none",
              "trim_whitespace": false,
              "alt": "",
              "rel": "",
              "link_class": "",
              "prefix": "",
              "suffix": "",
              "target": "",
              "nl2br": false,
              "max_length": 0,
              "word_boundary": false,
              "ellipsis": false,
              "more_link": false,
              "more_link_text": "",
              "more_link_path": "",
              "strip_tags": false,
              "trim": false,
              "preserve_tags": "",
              "html": false
            },
            "element_type": "",
            "element_class": "",
            "element_label_type": "",
            "element_label_class": "",
            "element_label_colon": false,
            "element_wrapper_type": "",
            "element_wrapper_class": "",
            "element_default_classes": true,
            "empty": "",
            "hide_empty": false,
            "empty_zero": false,
            "hide_alter_empty": true,
            "click_sort_column": "value",
            "type": "string",
            "settings": {
              "link_to_entity": true
            },
            "group_column": "value",
            "group_columns": {},
            "group_rows": true,
            "delta_limit": 0,
            "delta_offset": 0,
            "delta_reversed": false,
            "delta_first_last": false,
            "multi_type": "separator",
            "separator": ", ",
            "field_api_classes": false
          }
        },
        "arguments": {
          "nid": {
            "id": "nid",
            "table": "node_field_data",
            "field": "nid",
            "relationship": "none",
            "group_type": "group",
            "admin_label": "",
            "entity_type": "node",
            "entity_field": "nid",
            "plugin_id": "node_nid",
            "default_action": "default",
            "exception": {
              "value": "all",
              "title_enable": false,
              "title": "All"
            },
            "title_enable": false,
            "title": "",
            "default_argument_type": "node",
            "default_argument_options": {},
            "summary_options": {
              "base_path": "",
              "count": true,
              "override": false,
              "items_per_page": 25
            },
            "summary": {
              "sort_order": "asc",
              "number_of_records": 0,
              "format": "default_summary"
            },
            "specify_validation": false,
            "validate": {
              "type": "none",
              "fail": "not found"
            },
            "validate_options": {},
            "break_phrase": false,
            "not": false
          }
        },
        "filters": {
          "type": {
            "id": "type",
            "table": "node_field_data",
            "field": "type",
            "relationship": "reverse__node__field_all_people",
            "group_type": "group",
            "admin_label": "",
            "entity_type": "node",
            "entity_field": "type",
            "plugin_id": "bundle",
            "operator": "in",
            "value": {
              "documents": "documents"
            },
            "group": 1,
            "exposed": false,
            "expose": {
              "operator_id": "",
              "label": "",
              "description": "",
              "use_operator": false,
              "operator": "",
              "operator_limit_selection": false,
              "operator_list": {},
              "identifier": "",
              "required": false,
              "remember": false,
              "multiple": false,
              "remember_roles": {
                "authenticated": "authenticated"
              },
              "reduce": false
            },
            "is_grouped": false,
            "group_info": {
              "label": "",
              "description": "",
              "identifier": "",
              "optional": true,
              "widget": "select",
              "multiple": false,
              "remember": false,
              "default_group": "All",
              "default_group_multiple": {},
              "group_items": {}
            }
          }
        },
        "filter_groups": {
          "operator": "AND",
          "groups": {
            "1": "AND"
          }
        },
        "style": {
          "type": "html_list",
          "options": {
            "grouping": {},
            "row_class": "",
            "default_row_class": true,
            "type": "ul",
            "wrapper_class": "doc-list",
            "class": ""
          }
        },
        "row": {
          "type": "fields",
          "options": {
            "default_field_elements": true,
            "inline": {},
            "separator": "",
            "hide_empty": false
          }
        },
        "defaults": {
          "title": false,
          "style": false,
          "row": false,
          "relationships": false,
          "fields": false,
          "arguments": false,
          "filters": false,
          "filter_groups": false
        },
        "relationships": {
          "reverse__node__field_all_people": {
            "id": "reverse__node__field_all_people",
            "table": "node_field_data",
            "field": "reverse__node__field_all_people",
            "relationship": "none",
            "group_type": "group",
            "admin_label": "field_all_people",
            "entity_type": "node",
            "plugin_id": "entity_reverse",
            "required": false
          }
        },
        "display_description": "",
        "display_extenders": {},
        "block_hide_empty": true
      },
      "cache_metadata": {
        "max-age": -1,
        "contexts": {
          "0": "languages:language_content",
          "1": "languages:language_interface",
          "2": "url",
          "3": "url.query_args",
          "4": "user.node_grants:view",
          "5": "user.permissions"
        },
        "tags": {}
      }
    },
    "block_2": {
      "id": "block_2",
      "display_title": "Author",
      "display_plugin": "block",
      "position": 5,
      "display_options": {
        "title": "Author",
        "fields": {
          "title": {
            "id": "title",
            "table": "node_field_data",
            "field": "title",
            "relationship": "reverse__node__field_author",
            "group_type": "group",
            "admin_label": "",
            "entity_type": "node",
            "entity_field": "title",
            "plugin_id": "field",
            "label": "",
            "exclude": false,
            "alter": {
              "alter_text": false,
              "text": "",
              "make_link": false,
              "path": "",
              "absolute": false,
              "external": false,
              "replace_spaces": false,
              "path_case": "none",
              "trim_whitespace": false,
              "alt": "",
              "rel": "",
              "link_class": "",
              "prefix": "",
              "suffix": "",
              "target": "",
              "nl2br": false,
              "max_length": 0,
              "word_boundary": false,
              "ellipsis": false,
              "more_link": false,
              "more_link_text": "",
              "more_link_path": "",
              "strip_tags": false,
              "trim": false,
              "preserve_tags": "",
              "html": false
            },
            "element_type": "",
            "element_class": "",
            "element_label_type": "",
            "element_label_class": "",
            "element_label_colon": false,
            "element_wrapper_type": "",
            "element_wrapper_class": "",
            "element_default_classes": true,
            "empty": "",
            "hide_empty": false,
            "empty_zero": false,
            "hide_alter_empty": true,
            "click_sort_column": "value",
            "type": "string",
            "settings": {
              "link_to_entity": true
            },
            "group_column": "value",
            "group_columns": {},
            "group_rows": true,
            "delta_limit": 0,
            "delta_offset": 0,
            "delta_reversed": false,
            "delta_first_last": false,
            "multi_type": "separator",
            "separator": ", ",
            "field_api_classes": false
          }
        },
        "arguments": {
          "nid": {
            "id": "nid",

In [2]:
id_498 = pd.read_csv('498_export.csv')
id_498

,ID,Box,title,Document Date,Document Length,Manuscript Type,Collection,Source,Internal Notes,Workflow Stage,...,Document Body,Signature,Post Script,Document Extra,Marginalia,Enclosure,Footnote,General,Image Identifier,Response
0,498,Box 10 Folder 5,Reference Material for Speech concerning the c...,"Fri, 01/01/1999 - 12:00\n - Fri, 12/31/1999 - ...",260,Printed,Papers of Julian Bond 1897-2006,"Special Collections, University of Virginia Li...",Scanning Notes: There are two records associat...,Transcribed,...,[The following is one of five reference materi...,NaN,NaN,NaN,NaN,NaN,* Member of the New York Bar. Former General C...,NaN,"3242610, 3242611, 3242612, 3242613, 3242614, 3...",NaN

In [3]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [4]:
id_498

,ID,Box,title,Document Date,Document Length,Manuscript Type,Collection,Source,Internal Notes,Workflow Stage,Object Type,Author,Keywords,Document Top,Dateline,Salutation,Document Body,Signature,Post Script,Document Extra,Marginalia,Enclosure,Footnote,General,Image Identifier,Response
0,498,Box 10 Folder 5,Reference Material for Speech concerning the c...,"Fri, 01/01/1999 - 12:00\n - Fri, 12/31/1999 - ...",260,Printed,Papers of Julian Bond 1897-2006,"Special Collections, University of Virginia Li...",Scanning Notes: There are two records associat...,Transcribed,Ephemera,NaN,NaN,NaN,NaN,NaN,[The following is one of five reference materi...,NaN,NaN,NaN,NaN,NaN,* Member of the New York Bar. Former General C...,NaN,"3242610, 3242611, 3242612, 3242613, 3242614, 3...",NaN

In [7]:
print(id_498['Footnote'][0])

* Member of the New York Bar. Former General Counsel, National Association for the Advancement of Colored People. A.B. 1937, Lincoln University; LL.B. 1940, Howard University; LL.M. 1941, Columbia University. —Ed.
, 1. Plessy v. Ferguson, 163 U.S. 537 (1896).
, 2. F. FREUND, THE SUPREME COURT OF THE UNITED STATES 172-73 (1961). Actually, McLaurin v. Oklahoma State Regents, 339 U.S. 637 (1950), had forecast what the Court would decide in Brown.
, 3. 347 U.S. 483 (1954).
, 4. 305 U.S. 337 (1938).
, 5. 163 U.S. 537 (1896).
, 6. Lane v Wilson, 307 U.S. 268, 275 (1939).
, 7. Plessy v Ferguson, 163 U.S. 537 (1896).
, 8. Sweatt v. Painter, 339 U.S. 629 (1950).
, 9. McLaurin v. Oklahoma State Regents, 339 U.S. 637 (1950).
, 10. Watson v. Memphis, 373 U.S. 526 (1963); New Orleans City Park Improvements Assn. v. Detiege, 358 U.S. 54 (1958) (memorandum decision).
, 11. Gayle v. Browder, 352 U.S. 903 (1956) (memorandum decision).
, 12. Boynton v. Virginia, 364, U.S. 454 (1960) (application of Interstate Commerce Act).
, 13. Holmes v. City of Atlanta, 350 U.S. 879 (1955) (memorandum decision).
, 14. Watson v. Memphis, 373 U.S. 526 (1963); Mayor & City Council of Baltimore City v. Dawson, 350 U.S. 877 (1955) (memorandum decision).
, 15. Turner v. Memphis, 369 U.S. 762 (1962).
, 16. Thomas v. Mississippi, 380 U.S. 524 (1965); Boynton v. Virginia, 364 U.S. 903 (1956) (memorandum decision).
, 17. Brown v. Louisiana, 383 U.S. 131 (1966).
, 18. Burton v. Wilmington Parking Authority, 365 U.S. 715 (1961).
, 19. Johnson v. Virginia, 373 U.S. 61 (1963).
, 20. Anderson v. Martin, 375 U.S. 399 (1964).
, 21. Hamilton v. Alabama, 376 U.S. 650 (1964).
, 22. Loving v. Virginia, 388 U.S. 1 (1967).
, 23. McLaughlin v. Florida, 379 U.S. 184 (1964).
, 24. Cooper v. Aaron, 358 U.S. 1 (1958).
, 25. Griffin v. County School Bd. of Prince Edward County, 377 U.S. 218 (1964).