Goal here is to just write a little script to merge the proofreading excel sheet with the URLs to the IIIF images in FTP, hopefully to make proofreading a bit simpler.

**PREREQUISITE**

* Download fresh Doc Catalog: Go to Drupal --> Document Catalog --> CSV (needs to be up to date on "Workflow Stage" specifically). It is IMMENSELY useful to filter the Document Catalog before you export. You can either individually select the folders, or do what I do and just ballpark it using "ID greater than [some number that's a bit below the first ID in your box]"
* Check out ALL folders for a single box. This script operates at the box level, not folder level. Make sure ALL folders are ready to be added to single verification before proceeding!

**WHEN COMPLETE:**

Not yet done! Still need to copy/paste individual rows into Excel template. Instructions forthcoming after I remember how to do it

In [1]:
import pandas as pd
import numpy as np

catalog_path = 'catalog_09092026.csv'

catalog = pd.read_csv(catalog_path)

In [2]:
# TODO: consider maybe not naming all your variables by the box... this is kind of annoying to change

box_17 = catalog[catalog['Box'].str.startswith('Box 17', na=False)]

In [3]:
box_17.columns

Index(['ID', 'Box', 'title', 'Document Date', 'Document Length',
       'Manuscript Type', 'Collection', 'Source', 'Internal Notes',
       'Workflow Stage', 'Object Type', 'Author', 'Keywords', 'Document Top',
       'Dateline', 'Salutation', 'Document Body', 'Signature', 'Post Script',
       'Document Extra', 'Marginalia', 'Enclosure', 'Footnote', 'General',
       'Image Identifier', 'Response'],
      dtype='object')

In [4]:
box_17_cols = box_17[['ID', 'Box', 'title', 'Document Length', 'Workflow Stage', 'Image Identifier']]

In [5]:
box_17_cols

,ID,Box,title,Document Length,Workflow Stage,Image Identifier
2761,9203,Box 17 Folder 8,"To Julian Bond from Kofi Lomotey, ca. 1 Apr 1974",1.0,Transcribed,3407519
2762,9204,Box 17 Folder 8,"Fragment: To Julian Bond from Vi Patterson, 25...",1.0,Transcribed,3407520
2763,9205,Box 17 Folder 8,"From Julian Bond to Livingstone Johnson, 30 Ap...",1.0,Transcribed,3407521
2764,9206,Box 17 Folder 8,"From Julian Bond to C. L. Clifton, 30 Apr 1974",1.0,Transcribed,3407522
2765,9207,Box 17 Folder 8,"From Julian Bond to Earnest Pharr, 30 Apr 1974",1.0,Transcribed,3407523
...,...,...,...,...,...,...
4009,7956,Box 17 Folder 1,"From Julian Bond to Sid Haddad, 2 Jul 1973",1.0,Transcribed,3457622
4010,7957,Box 17 Folder 1,"From Julian Bond to Yancey [Martin], 2 Jul 1973",1.0,Transcribed,3457623
4011,7958,Box 17 Folder 1,"From Julian Bond to Herb Trawick, 2 Jul 1973",1.0,Transcribed,3457624
4012,7959,Box 17 Folder 1,"From Julian Bond to Pat Patterson, 2 Jul 1973",1.0,Transcribed,3457625
4013,7960,Box 17 Folder 1,"From Julian Bond to Lonnell Conley, 2 Jul 1973",1.0,Transcribed,3457626

In [6]:
box_17_cols['has_images'] = np.where(box_17_cols['Image Identifier'].notna(), 'Has images in Drupal', 'Does not have images in Drupal')

C:\Users\charl\AppData\Local\Temp\ipykernel_24872\425507693.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  box_17_cols['has_images'] = np.where(box_17_cols['Image Identifier'].notna(), 'Has images in Drupal', 'Does not have images in Drupal')

In [7]:
box_17_cols.has_images.value_counts()

has_images
Has images in Drupal    1000
Name: count, dtype: int64

In [8]:
box_17_cols['Document Length'] = box_17_cols['Document Length'].astype(int)

C:\Users\charl\AppData\Local\Temp\ipykernel_24872\1136337504.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  box_17_cols['Document Length'] = box_17_cols['Document Length'].astype(int)

In [9]:
box_17_cols.Box.unique()

array(['Box 17 Folder 8', 'Box 17 Folder 7', 'Box 17 Folder 6',
       'Box 17 Folder 5', 'Box 17 Folder 4', 'Box 17 Folder 3',
       'Box 17 Folder 2', 'Box 17 Folder 1'], dtype=object)

In [10]:
box_17_cols[box_17_cols['Workflow Stage'] == 'Early Access']

Empty DataFrame
Columns: [ID, Box, title, Document Length, Workflow Stage, Image Identifier, has_images]
Index: []

In [12]:
# anything that comes up in this box, needs to be highlighted in the final Excel sheet so that people don't work on it!

box_17_cols[box_17_cols['Workflow Stage'] != 'Transcribed']

,ID,Box,title,Document Length,Workflow Stage,Image Identifier,has_images
3551,8425,Box 17 Folder 4,DO NOT PUBLISH: To Fred Whitehead from O. F. B...,2,Cataloged,"3386416, 3386417",Has images in Drupal

In [13]:
box_17_cols.to_csv('box_17_cols.csv')

Once this is exported, it's pretty simple. First, highlight everything --> Sort --> Custom Sort --> Column: ID, smallest to largest. This puts everything in ascending order. Then you just Ctrl+Shift+Down each column to select the whole column, then Ctrl+V into the corresponding column in the template. NOTE: they are not in the same order! I know this is odd and I apologize. I can change it if anyone wants me to. DOUBLE NOTE: You don't need to paste the "Image Identifier" column anywhere.