Goal here is to just write a little script to merge the proofreading excel sheet with the URLs to the IIIF images in FTP, hopefully to make proofreading a bit simpler.

In [5]:
import pandas as pd
import numpy as np

catalog_path = 'catalog_01072025.csv'

catalog = pd.read_csv(catalog_path)

In [12]:
box_16 = catalog[catalog['Box'].str.startswith('Box 16', na=False)]

In [15]:
box_16.columns

Index(['index', 'ID', 'Box', 'title', 'Document Date', 'Document Length',
       'Manuscript Type', 'Collection', 'Source', 'Internal Notes',
       'Workflow Stage', 'Object Type', 'Author', 'Keywords', 'Document Top',
       'Dateline', 'Salutation', 'Document Body', 'Signature', 'Post Script',
       'Document Extra', 'Marginalia', 'Enclosure', 'Footnote', 'General',
       'Image Identifier', 'Response'],
      dtype='object')

In [30]:
box_16_cols = box_16[['ID', 'Box', 'title', 'Document Length', 'Workflow Stage', 'Image Identifier']]

In [31]:
box_16_cols

,ID,Box,title,Document Length,Workflow Stage,Image Identifier
0,7942,Box 16 Folder 7,"From Julian Bond to Mrs. Leonel Burns, 31 Jan ...",1.0,Transcribed,3467767
1,7943,Box 16 Folder 7,"From Julian Bond to Bill James, 31 Jan 1973",1.0,Transcribed,3467768
2,7944,Box 16 Folder 7,"From Julian Bond to Elton Morris, 31 Jan 1973",1.0,Transcribed,3467769
3,7945,Box 16 Folder 7,"From Julian Bond to Ofield Dukes, 31 Jan 1973",1.0,Transcribed,3467770
4,7946,Box 16 Folder 7,"From Julian Bond to Roger Hickey, 31 Jan 1973",2.0,Transcribed,"3467771, 3467772"
...,...,...,...,...,...,...
1866,6935,Box 16 Folder 3,"From Julian Bond to David Dunn, 30 May 1972",1.0,Transcribed,3465912
1867,6936,Box 16 Folder 3,"From Julian Bond to C. B. King, 30 May 1972",1.0,Transcribed,3465913
1868,6937,Box 16 Folder 3,"From Julian Bond to Joi Thompson, 30 May 1972",1.0,Transcribed,3465914
1869,6938,Box 16 Folder 3,"From Julian Bond to Bryce Smith, 30 May 1972",1.0,Transcribed,3465915
1870,6939,Box 16 Folder 3,"From Julian Bond to E. J. Brisker, 30 May 1972",1.0,Transcribed,3465916

In [32]:
box_16_cols['has_images'] = np.where(box_16_cols['Image Identifier'].notna(), 'Has images in Drupal', 'Does not have images in Drupal')

C:\Users\charl\AppData\Local\Temp\ipykernel_24504\4176223013.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  box_16_cols['has_images'] = np.where(box_16_cols['Image Identifier'].notna(), 'Has images in Drupal', 'Does not have images in Drupal')

In [33]:
box_16_cols.has_images.value_counts()

has_images
Has images in Drupal              1862
Does not have images in Drupal       9
Name: count, dtype: int64

In [34]:
box_16_cols['Document Length'] = box_16_cols['Document Length'].astype(int)

C:\Users\charl\AppData\Local\Temp\ipykernel_24504\3317523698.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  box_16_cols['Document Length'] = box_16_cols['Document Length'].astype(int)

In [35]:
box_16_cols.Box.unique()

array(['Box 16 Folder 7', 'Box 16 Folder 6', 'Box 16 Folder 5',
       'Box 16 Folder 4', 'Box 16 Folder 1', 'Box 16 Folder 2',
       'Box 16 Folder 3'], dtype=object)

In [36]:
box_16_cols[box_16_cols['Workflow Stage'] == 'Early Access']

,ID,Box,title,Document Length,Workflow Stage,Image Identifier,has_images
92,7835,Box 16 Folder 7,"To Julian Bond from Pat Lewis, 11 Dec 1973, wi...",4,Early Access,"3467644, 3467645, 3467646, 3467647",Has images in Drupal
135,7833,Box 16 Folder 7,"[Copy 1] From Julian Bond to Stewart Lewis, 4 ...",1,Early Access,3467642,Has images in Drupal

In [38]:
box_16_cols.to_csv('box_16_cols.csv')